# Generated by Django 6.1 on 2026-08-22 05:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado'), ('utilizado', 'Utilizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ticketmaster', 'Ticketmaster'), ('tmdb', 'TMDb')], max_length=20, verbose_name='Provedor')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID externo')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem_url', models.URLField(blank=True, verbose_name='Imagem')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('data_origem', models.DateTimeField(blank=True, null=True, verbose_name='Data original')),
                ('dados_json', models.JSONField(blank=True, default=dict, verbose_name='Dados da API')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item do catálogo externo',
                'verbose_name_plural': 'Itens do catálogo externo',
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_external_id')],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('digital', 'Conteúdo Digital')], default='presencial', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de término')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('capacidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade')),
                ('local', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='app.catalogoexterno', verbose_name='Item do catálogo')),
                ('organizador', models.ForeignKey(limit_choices_to={'role': 'organizador'}, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('fila', models.CharField(blank=True, max_length=10, verbose_name='Fila')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='app.evento', verbose_name='Evento')),
            ],
            options={
                'ordering': ['fila', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='app.ingresso', verbose_name='Ingresso')),
            ],
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'role': 'portaria'}, on_delete=django.db.models.deletion.CASCADE, related_name='portaria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendente', max_length=20, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app.assento', verbose_name='Assento')),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'cliente'}, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='app.evento', verbose_name='Evento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('metodo', models.CharField(choices=[('simulado', 'Pagamento simulado'), ('cartao', 'Cartão'), ('pix', 'PIX')], default='simulado', max_length=20, verbose_name='Método')),
                ('transacao_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da transação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='app.reserva', verbose_name='Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='ingresso',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ingresso', to='app.reserva', verbose_name='Reserva'),
        ),
        migrations.AddConstraint(
            model_name='assento',
            constraint=models.UniqueConstraint(fields=('evento', 'codigo'), name='unique_seat_per_event'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'confirmada'])), fields=('evento', 'assento'), name='unique_active_seat_reservation'),
        ),
    ]
