# Generated by Django 6.1 on 2026-08-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ingresso_catalogoexterno_evento_assento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validado_em', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('ingresso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='validacao', to='app.ingresso', verbose_name='Ingresso')),
                ('portaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validacoes', to='app.portaria', verbose_name='Portaria')),
            ],
        ),
    ]
